[![Build Status](http://drone.i-buzz-system.com/api/badges/ibuzztw/louie_cicd/status.svg)](http://drone.i-buzz-system.com/ibuzztw/louie_cicd)

kind: pipeline
type: docker
name: default

steps:
- name: frontend
  image: node
  commands:
  - npm install
  - npm run test:unit


